# Generated by Django 3.0.2 on 2020-01-19 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='timer',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
