# Generated by Django 3.0.2 on 2020-01-19 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20200119_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='timer',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
